global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'reviewservice'
    metrics_path: /metrics
    static_configs:
      - targets: ['webshop.review:8080']  # Use the container's internal port
